// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncProducer creates a new instance of MockSyncProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncProducer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSyncProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSyncProducer is an autogenerated mock type for the SyncProducer type
type MockSyncProducer struct {
	mock.Mock
}

type MockSyncProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncProducer) EXPECT() *MockSyncProducer_Expecter {
	return &MockSyncProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSyncProducer
func (_mock *MockSyncProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSyncProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSyncProducer_Expecter) Close() *MockSyncProducer_Close_Call {
	return &MockSyncProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSyncProducer_Close_Call) Run(run func()) *MockSyncProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSyncProducer_Close_Call) Return(err error) *MockSyncProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncProducer_Close_Call) RunAndReturn(run func() error) *MockSyncProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockSyncProducer
func (_mock *MockSyncProducer) Commit(topic string, key []byte, value []byte, headers []sarama.RecordHeader) error {
	ret := _mock.Called(topic, key, value, headers)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, []byte, []sarama.RecordHeader) error); ok {
		r0 = returnFunc(topic, key, value, headers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncProducer_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockSyncProducer_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - topic string
//   - key []byte
//   - value []byte
//   - headers []sarama.RecordHeader
func (_e *MockSyncProducer_Expecter) Commit(topic any, key any, value any, headers any) *MockSyncProducer_Commit_Call {
	return &MockSyncProducer_Commit_Call{Call: _e.mock.On("Commit", topic, key, value, headers)}
}

func (_c *MockSyncProducer_Commit_Call) Run(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader)) *MockSyncProducer_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []sarama.RecordHeader
		if args[3] != nil {
			arg3 = args[3].([]sarama.RecordHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSyncProducer_Commit_Call) Return(err error) *MockSyncProducer_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncProducer_Commit_Call) RunAndReturn(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader) error) *MockSyncProducer_Commit_Call {
	_c.Call.Return(run)
	return _c
}
