// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAsyncProducer creates a new instance of MockAsyncProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsyncProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsyncProducer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAsyncProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAsyncProducer is an autogenerated mock type for the AsyncProducer type
type MockAsyncProducer struct {
	mock.Mock
}

type MockAsyncProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsyncProducer) EXPECT() *MockAsyncProducer_Expecter {
	return &MockAsyncProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockAsyncProducer
func (_mock *MockAsyncProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAsyncProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAsyncProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAsyncProducer_Expecter) Close() *MockAsyncProducer_Close_Call {
	return &MockAsyncProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAsyncProducer_Close_Call) Run(run func()) *MockAsyncProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAsyncProducer_Close_Call) Return(err error) *MockAsyncProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAsyncProducer_Close_Call) RunAndReturn(run func() error) *MockAsyncProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Fire provides a mock function for the type MockAsyncProducer
func (_mock *MockAsyncProducer) Fire(topic string, key []byte, value []byte, headers []sarama.RecordHeader) {
	_mock.Called(topic, key, value, headers)
	return
}

// MockAsyncProducer_Fire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fire'
type MockAsyncProducer_Fire_Call struct {
	*mock.Call
}

// Fire is a helper method to define mock.On call
//   - topic string
//   - key []byte
//   - value []byte
//   - headers []sarama.RecordHeader
func (_e *MockAsyncProducer_Expecter) Fire(topic any, key any, value any, headers any) *MockAsyncProducer_Fire_Call {
	return &MockAsyncProducer_Fire_Call{Call: _e.mock.On("Fire", topic, key, value, headers)}
}

func (_c *MockAsyncProducer_Fire_Call) Run(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader)) *MockAsyncProducer_Fire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []sarama.RecordHeader
		if args[3] != nil {
			arg3 = args[3].([]sarama.RecordHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAsyncProducer_Fire_Call) Return() *MockAsyncProducer_Fire_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncProducer_Fire_Call) RunAndReturn(run func(topic string, key []byte, value []byte, headers []sarama.RecordHeader)) *MockAsyncProducer_Fire_Call {
	_c.Run(run)
	return _c
}
