// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"backend/onlineconversation/internal/dto"
	"backend/onlineconversation/internal/projection"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockModerationClient creates a new instance of MockModerationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModerationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModerationClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockModerationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockModerationClient is an autogenerated mock type for the ModerationClient type
type MockModerationClient struct {
	mock.Mock
}

type MockModerationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModerationClient) EXPECT() *MockModerationClient_Expecter {
	return &MockModerationClient_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockModerationClient
func (_mock *MockModerationClient) Evaluate(ctx context.Context, contents projection.Contents) (dto.Verdict, error) {
	ret := _mock.Called(ctx, contents)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 dto.Verdict
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, projection.Contents) (dto.Verdict, error)); ok {
		return returnFunc(ctx, contents)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, projection.Contents) dto.Verdict); ok {
		r0 = returnFunc(ctx, contents)
	} else {
		r0 = ret.Get(0).(dto.Verdict)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, projection.Contents) error); ok {
		r1 = returnFunc(ctx, contents)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModerationClient_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockModerationClient_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - contents projection.Contents
func (_e *MockModerationClient_Expecter) Evaluate(ctx any, contents any) *MockModerationClient_Evaluate_Call {
	return &MockModerationClient_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, contents)}
}

func (_c *MockModerationClient_Evaluate_Call) Run(run func(ctx context.Context, contents projection.Contents)) *MockModerationClient_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 projection.Contents
		if args[1] != nil {
			arg1 = args[1].(projection.Contents)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModerationClient_Evaluate_Call) Return(verdict dto.Verdict, err error) *MockModerationClient_Evaluate_Call {
	_c.Call.Return(verdict, err)
	return _c
}

func (_c *MockModerationClient_Evaluate_Call) RunAndReturn(run func(ctx context.Context, contents projection.Contents) (dto.Verdict, error)) *MockModerationClient_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// Model provides a mock function for the type MockModerationClient
func (_mock *MockModerationClient) Model() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Model")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockModerationClient_Model_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Model'
type MockModerationClient_Model_Call struct {
	*mock.Call
}

// Model is a helper method to define mock.On call
func (_e *MockModerationClient_Expecter) Model() *MockModerationClient_Model_Call {
	return &MockModerationClient_Model_Call{Call: _e.mock.On("Model")}
}

func (_c *MockModerationClient_Model_Call) Run(run func()) *MockModerationClient_Model_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModerationClient_Model_Call) Return(s string) *MockModerationClient_Model_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockModerationClient_Model_Call) RunAndReturn(run func() string) *MockModerationClient_Model_Call {
	_c.Call.Return(run)
	return _c
}
