name: auth
on:
  push:
    branches:
      - main
    paths:
      - 'backend/auth/**'
      - '.github/workflows/auth.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/auth
      dockerfile: ./backend/auth/Dockerfile
      context: ./backend
