name: chat
on:
  push:
    branches:
      - main
    paths:
      - 'backend/chat/**'
      - 'backend/common/**'
      - '.github/workflows/chat.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/chat
      dockerfile: ./backend/chat/Dockerfile
      context: ./backend
