name: expo-notification
on:
  push:
    branches:
      - main
    paths:
      - 'backend/expo-notification/**'
      - '.github/workflows/expo-notification.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/expo-notification
      dockerfile: ./backend/expo-notification/Dockerfile
      context: ./backend/expo-notification
