name: fcmnotification
on:
  push:
    branches:
      - main
    paths:
      - 'backend/fcmnotification/**'
      - 'backend/common/**'
      - '.github/workflows/fcmnotification.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/fcmnotification
      dockerfile: ./backend/fcmnotification/Dockerfile
      context: ./backend
