name: messagepreprocess
on:
  push:
    branches:
      - main
    paths:
      - 'backend/messagepreprocess/**'
      - 'backend/common/**'
      - '.github/workflows/messagepreprocess.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/messagepreprocess
      dockerfile: ./backend/messagepreprocess/Dockerfile
      context: ./backend
