name: messagepersist
on:
  push:
    branches:
      - main
    paths:
      - 'backend/messagepersist/**'
      - 'backend/common/**'
      - '.github/workflows/messagepersist.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/messagepersist
      dockerfile: ./backend/messagepersist/Dockerfile
      context: ./backend
