name: messagerelay
on:
  push:
    branches:
      - main
    paths:
      - 'backend/messagerelay/**'
      - 'backend/common/**'
      - '.github/workflows/messagerelay.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/messagerelay
      dockerfile: ./backend/messagerelay/Dockerfile
      context: ./backend
