name: schedulednotificationjob
on:
  push:
    branches:
      - main
    paths:
      - 'backend/schedulednotificationjob/**'
      - '.github/workflows/schedulednotificationjob.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: flink/schedulednotificationjob
      dockerfile: ./backend/schedulednotificationjob/Dockerfile
      context: ./backend/schedulednotificationjob
