name: search
on:
  push:
    branches:
      - main
    paths:
      - 'backend/search/**'
      - '.github/workflows/search.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/search
      dockerfile: ./backend/search/Dockerfile
      context: ./backend/search
