name: turn
on:
  push:
    branches:
      - main
    paths:
      - 'backend/turn/**'
      - 'backend/common/**'
      - '.github/workflows/turn.yml'
      - '.github/workflows/build-and-deploy.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      image: backend/turn
      dockerfile: ./backend/turn/Dockerfile
      context: ./backend
